services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hr_db
      DB_USERNAME: hr
      DB_PASSWORD: root123

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hr_db
      MYSQL_USER: hr
      MYSQL_PASSWORD: root123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
